# Generated by Django 5.1.1 on 2024-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('VV', 'Verdadeiro/Verdadeiro'), ('VF', 'Verdadeiro/Falso'), ('FF', 'Falso/Falso')], max_length=2)),
            ],
        ),
    ]
